# Generated by Django 3.1 on 2023-01-18 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('width_field', models.IntegerField(default=400)),
                ('height_field', models.IntegerField(default=400)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field')),
            ],
        ),
    ]
