# Generated by Django 3.1 on 2023-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230119_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=200),
        ),
    ]
